spring:
  application:
    name: sms-service
  profiles.active: development
  
---
spring: 
  profiles: development
aws:
  accesskey: ""
  secretkey: ""
  senderid: "IAMFROM"
  smstype: "Transactional"
template.service:
  url: http://localhost:6015/iamfrom/v1/generatemessage 
logging:
  file: /opt/log/iamfrom-sms-service/application.log
  level:
    com.sms.service: debug 
server: 
  port: 6017
  
---
spring: 
  profiles: uat
aws:
  accesskey: ""
  secretkey: ""
  senderid: "IAMFROM"
  smstype: "Transactional"
template.service:
  url: http://localhost:6015/iamfrom/v1/generatemessage 
logging:
  file: /opt/log/iamfrom-sms-service/application.log
  level:
    com.sms.service: debug 
server: 
  port: 6017
   

---
spring: 
  profiles: production
aws:
  accesskey: ""
  secretkey: ""
  senderid: "IAMFROM"
  smstype: "Transactional"
template.service:
  url: http://localhost:6015/iamfrom/v1/generatemessage
logging:
  file: /opt/log/iamfrom-sms-service/application.log
  level:
    com.sms.service: debug 
server: 
  port: 6017
 
 
   
